name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - stg

  workflow_dispatch:
    inputs:
      force:
        description: 'Force exec'
        type: boolean
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Env
        run: |
          COMMIT_SHORT_SHA=`git rev-parse --short ${GITHUB_SHA}`
          COMMIT_TIME=`git show -s --format=%ct HEAD`

          echo "COMMIT_SHORT_SHA=${COMMIT_SHORT_SHA}" >> $GITHUB_ENV
          echo "COMMIT_TIME=${COMMIT_TIME}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image & Push
        uses: netcorext/buildx-image-action@dev
        with:
          image: netcorext/pev2
          tag: ${{ env.COMMIT_TIME }}
          tag-hash: ${{ env.COMMIT_SHORT_SHA }}
          tag-latest: latest
